sudo: false

language: node_js

# Use node 8 for build
node_js:
  - "8"

# Then test with specific node version
env:
  - TEST_NODE_VERSION="0.10"
  - TEST_NODE_VERSION="0.12"
  - TEST_NODE_VERSION="4"
  - TEST_NODE_VERSION="6"
  - TEST_NODE_VERSION="8"

before_install:
  - node --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

install:
  - yarn
  - nvm install $TEST_NODE_VERSION
  - npm install -g grunt

os:
  - osx
  - linux

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - env: "NODE_VERSION=7"

script:
  - nvm use $TRAVIS_NODE_VERSION
  - node --version && npm --version && git --version && svn --version | head -n 1
  - grunt travis
